# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RiseOfSkills' do
  use_frameworks!

  # Pods for RiseOfSkills
  pod 'Alamofire',  '~> 4.4.0'
  pod 'RealmSwift', '~> 2.8.3'

end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end

